swagger: "2.0"
info:
  description: "This is the pill dispenser medication API."
  version: "1.0.0"
  title: "Medication API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "bocaletm@oregonstate.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "medication-api:8080"
basePath: "/v2"
tags:
- name: "medication"
  description: "Medications available in pill dispenser"
  externalDocs:
    description: "Project Documentation"
    url: "https://bocaletm.github.io/cs361-group11-project/"
schemes:
- "https"
- "http"
paths:
  /medication:
    post:
      tags:
      - "medication"
      summary: "Add a new medication to the database"
      description: ""
      operationId: "addMed"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Medication object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Medication"
      responses:
        405:
          description: "Invalid input"
    put:
      tags:
      - "medication"
      summary: "Update an existing medication"
      description: ""
      operationId: "updateMed"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Medication object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Medication"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Medication not found"
        405:
          description: "Validation exception"
  /medication/getByPatientId/{patient_id}:
    get:
      tags:
      - "medication"
      summary: "Returns Medication Data for Any Medication in the System"
      description: "Muliple names can be provided with comma separated strings. Use med1, med2, med3 for testing."
      operationId: "getByPatientId"
      produces:
      - "application/json"
      parameters:
      - name: "patient_id"
        in: "path"
        description: "The patient whose medication list needs to be fetched."
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Medication"
        400:
          description: "Invalid name"
definitions:
  Medication:
    type: "object"
    required:
    - "id"
    - "patient_id"
    - "name"
    - "dose_date"
    properties:
      id:
        type: "integer"
        example: "1"
      patient_id:
        type: "integer"
        example: "1"
      name:
        type: "string"
        example: "acetaminophen"
      dose_date:
        type: "string"
        format: "date-time"
        example: "2017-07-21T17:32:28Z"
      nih-url:
        type: "string"
        example: "https://druginfo.nlm.nih.gov/drugportal/name/acetaminophen"
      contraindications:
        type: "array"
        items:
          type: "string"
          example: 
            - "ethanol"
            - "sodium nitrite"
externalDocs:
  description: "Check out the project portfolio"
  url: "https://bocaletm.github.io/cs361-group11-project/"
