version: '3'
services:
  medication-app:
    image: medication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - JHIPSTER_SLEEP=60 # gives time for other services to boot before the application
    ports:
      - 8080:8080
    depends_on:
      - medication-mysql
    networks:
      - medication-overlay
  medication-mysql:
    image: mysql:8.0.17
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: medication
    ports:
      - "3308:3306"
    networks: 
      - medication-overlay
networks:
  medication-overlay:
    external:
      name: medication-overlay
